name: ES Lint Check

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm run lint
